export enum Marcas {
    TOYOTA = "Toyota",
    FORD = "Ford",
    CHEVROLET = "Chevrolet",
    HONDA = "Honda",
    NISSAN = "Nissan",
}

export const BDTienda = {
    clientes: [
        {
            nombre: "Juan PÃ©rez",
            documento: "77068189",
            codigo: "CL-001",
        },
        {
            nombre: "MarÃ­a GarcÃ­a",
            documento: "67068189",
            codigo: "CL-002",
        },
        {
            nombre: "Carlos RodrÃ­guez",
            documento: "27068189",
            codigo: "CL-003",
        },
        {
            nombre: "Carlos RodrÃ­guez",
            documento: "2758189",
            codigo: "CL-004",
        },
        {
            nombre: "Ruth Zeballos",
            documento: "27064189",
            codigo: "CL-005",
        },
        {
            nombre: "Karina Manrrique",
            documento: "27018189",
            codigo: "CL-006",
        },
        {
            nombre: "Carla Bastidas",
            documento: "27028189",
            codigo: "CL-007",
        },
    ],
    vehiculos: [
        {
            nombre: "Ford Mustang",
            marca: Marcas.FORD,
            vendido: true,
            precio: 5000,
            codigo: "VL-001",
        },
        {
            nombre: "Chevrolet Camaro",
            marca: Marcas.CHEVROLET,
            vendido: false,
            precio: 6000,
            codigo: "VL-002",
        },
        {
            nombre: "Toyota Corolla",
            marca: Marcas.TOYOTA,
            vendido: true,
            precio: 7000,
            codigo: "VL-003",
        },
        {
            nombre: "Honda Civic",
            marca: Marcas.HONDA,
            vendido: true,
            precio: 5500,
            codigo: "VL-004",
        },
        {
            nombre: "Nissan GT-R",
            marca: Marcas.NISSAN,
            vendido: true,
            precio: 8000,
            codigo: "VL-005",
        },
        {
            nombre: "Mazda MX-5",
            marca: Marcas.TOYOTA,
            vendido: true,
            precio: 4500,
            codigo: "VL-006",
        },
        {
            nombre: "BMW M3",
            marca: Marcas.FORD,
            vendido: false,
            precio: 9000,
            codigo: "VL-007",
        },
        {
            nombre: "Mercedes-Benz C-Class",
            marca: Marcas.CHEVROLET,
            vendido: false,
            precio: 8500,
            codigo: "VL-008",
        },
        {
            nombre: "Audi A4",
            marca: Marcas.HONDA,
            vendido: true,
            precio: 7500,
            codigo: "VL-009",
        },
        {
            nombre: "Volkswagen Golf",
            marca: Marcas.NISSAN,
            vendido: false,
            precio: 4000,
            codigo: "VL-010",
        },
        {
            nombre: "Toyota Corolla",
            marca: Marcas.TOYOTA,
            vendido: true,
            precio: 6000,
            codigo: "VL-011",
        },
        {
            nombre: "Ford Explorer",
            marca: Marcas.FORD,
            vendido: true,
            precio: 4000,
            codigo: "VL-012",
        },
        {
            nombre: "Chevrolet Silverado",
            marca: Marcas.CHEVROLET,
            vendido: false,
            precio: 12000,
            codigo: "VL-013",
        },
        {
            nombre: "Honda Accord",
            marca: Marcas.HONDA,
            vendido: true,
            precio: 4000,
            codigo: "VL-014",
        },
        {
            nombre: "Nissan Maxima",
            marca: Marcas.NISSAN,
            vendido: true,
            precio: 8500,
            codigo: "VL-015",
        },
        {
            nombre: "Toyota Camry",
            marca: Marcas.TOYOTA,
            vendido: true,
            precio: 12000,
            codigo: "VL-016",
        },
        {
            nombre: "Ford Mustang",
            marca: Marcas.FORD,
            vendido: false,
            precio: 12000,
            codigo: "VL-017",
        },
        {
            nombre: "Chevrolet Impala",
            marca: Marcas.CHEVROLET,
            vendido: false,
            precio: 8500,
            codigo: "VL-018",
        },
        {
            nombre: "Honda Civic",
            marca: Marcas.NISSAN,
            vendido: true,
            precio: 4000,
            codigo: "VL-019",
        },
        {
            nombre: "Nissan Altima",
            marca: Marcas.NISSAN,
            vendido: false,
            precio: 8500,
            codigo: "VL-020",
        }

    ],
    ventas: [
        {
            cliente: "CL-001",
            vehiculo: "VL-001",
            fechaCompra: "2003-12-01",
            codigo: "COMP-0001",
        },
        {
            cliente: "CL-002",
            vehiculo: "VL-002",
            fechaCompra: "2003-12-02",
            codigo: "COMP-0002",
        },
        {
            cliente: "CL-003",
            vehiculo: "VL-003",
            fechaCompra: "2003-12-03",
            codigo: "COMP-0003",
        },
        {
            cliente: "CL-001",
            vehiculo: "VL-004",
            fechaCompra: "2003-12-04",
            codigo: "COMP-0004",
        },
        {
            cliente: "CL-002",
            vehiculo: "VL-005",
            fechaCompra: "2003-12-05",
            codigo: "COMP-0005",
        },
        {
            cliente: "CL-004",
            vehiculo: "VL-006",
            fechaCompra: "2003-12-06",
            codigo: "COMP-0006",
        },
        {
            cliente: "CL-001",
            vehiculo: "VL-007",
            fechaCompra: "2003-12-07",
            codigo: "COMP-0007",
        },
        {
            cliente: "CL-005",
            vehiculo: "VL-008",
            fechaCompra: "2003-12-08",
            codigo: "COMP-0008",
        },
        {
            cliente: "CL-003",
            vehiculo: "VL-009",
            fechaCompra: "2003-12-09",
            codigo: "COMP-0009",
        },
        {
            cliente: "CL-006",
            vehiculo: "VL-010",
            fechaCompra: "2003-12-10",
            codigo: "COMP-0010",
        },
        {
            cliente: "CL-001",
            vehiculo: "VL-011",
            fechaCompra: "2003-12-10",
            codigo: "COMP-0011",
        },
        {
            cliente: "CL-007",
            vehiculo: "VL-012",
            fechaCompra: "2003-12-10",
            codigo: "COMP-0012",
        },
        {
            cliente: "CL-001",
            vehiculo: "VL-013",
            fechaCompra: "2003-12-10",
            codigo: "COMP-0013",
        },
        {
            cliente: "CL-002",
            vehiculo: "VL-014",
            fechaCompra: "2003-12-10",
            codigo: "COMP-0014",
        },
        {
            cliente: "CL-005",
            vehiculo: "VL-015",
            fechaCompra: "2003-12-10",
            codigo: "COMP-0015",
        },
        {
            cliente: "CL-006",
            vehiculo: "VL-016",
            fechaCompra: "2003-12-10",
            codigo: "COMP-0016",
        },
        {
            cliente: "CL-007",
            vehiculo: "VL-017",
            fechaCompra: "2003-12-10",
            codigo: "COMP-0017",
        },
    ],
};
